version: '3'
app:
     volumes:
       - "./app:/src"
     ports:
       - "3000:3000"
       - "35729:35729"
     build: ./app
services:
        solidserver:
                image: nodesolidserver/node-solid-server
                container_name: solidserver
                ports:
                - "8443:8443"
        sampleweb:
                build: .
                ports:
                - "3000:3000"